[package]
name = "seqkit"
version = "0.1.0"
authors = ["Matti Annala <matti.annala@uta.fi>"]

[dependencies]
docopt = "1.0"
bio = "0.19"
rust-htslib = "0.15"
regex = "1.0"
rand = "0.5"

[[bin]]
name = "fasta"
path = "src/fasta_main.rs"

[[bin]]
name = "sam"
path = "src/sam_main.rs"
