[package]
name = "seqkit"
version = "0.1.0"
authors = ["Matti Annala <matti.annala@uta.fi>"]

[dependencies]
docopt = "*"
bio = "*"
rust-htslib = "0.15.0"
flate2 = "*"
ascii = "*"
num-traits = "0.1.40"

[[bin]]
name = "fasta"
path = "src/fasta/main.rs"

[[bin]]
name = "sam"
path = "src/sam/main.rs"
